/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"

bool_t
xdr_Posicion (XDR *xdrs, Posicion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Uber (XDR *xdrs, Uber *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->placas, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->disponible))
		 return FALSE;
	 if (!xdr_Posicion (xdrs, &objp->posicion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tarifa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Servicio (XDR *xdrs, Servicio *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->viajesRealizados))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numAutos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ganancia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TerminarViajeArgs (XDR *xdrs, TerminarViajeArgs *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_Posicion (xdrs, &objp->final))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->costoViaje))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->placas, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
