/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "uber.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Uber *
solicitarviaje_1(Posicion pasajero,  CLIENT *clnt)
{
	static Uber clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, solicitarViaje,
		(xdrproc_t) xdr_Posicion, (caddr_t) &pasajero,
		(xdrproc_t) xdr_Uber, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
terminarviaje_1(TerminarViajeArgs args,  CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TerminarViaje,
		(xdrproc_t) xdr_TerminarViajeArgs, (caddr_t) &args,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

Servicio *
estadoservicio_1(CLIENT *clnt)
{
	static Servicio clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, estadoServicio, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_Servicio, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
