/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "uber.h"


void
uber_prog_1(char *host)
{
	CLIENT *clnt;
	Uber  *result_1;
	Posicion solicitarviaje_1_pasajero;
	void  *result_2;
	TerminarViajeArgs terminarviaje_1_args;
	Servicio  *result_3;

#ifndef	DEBUG
	clnt = clnt_create (host, uber_prog, uber_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = solicitarviaje_1(solicitarviaje_1_pasajero, clnt);
	if (result_1 == (Uber *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = terminarviaje_1(terminarviaje_1_args, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = estadoservicio_1(clnt);
	if (result_3 == (Servicio *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	uber_prog_1 (host);

	//cliente o administrador
	int opcion;
	printf("Seleccione una opcion:\n1. Cliente\n2. Administrador\n");
	scanf("%d", &opcion);
	srand(time(NULL));
	//Posicion pasajero aleatoria
	Posicion pasajero;
	pasajero.x = rand() % 50;
	pasajero.y = rand() % 50;
	//Cliente
	if (opcion == 1) {
	
		if(solicitarviaje_1(pasajero)!=NULL){
			printf("Viaje solicitado exitosamente.\n");
			sleep(5); // Simula el tiempo del viaje

			


			TerminarViajeArgs args;
			args.pasajero = pasajero;


			if(terminarviaje_1(args)!=NULL){
				printf("Viaje terminado exitosamente.\n");
			}else{
				printf("Error al terminar el viaje.\n");
			}
		}else{
			printf("Error al solicitar el viaje.\n");	
		}
	
	} 


	//Administrador
	else if (opcion == 2)
	{
		do
		{
			sleep(2);
			estadoservicio_1();
			
		} while (1);
		
	}
	
exit (0);
}
