/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UBER_H_RPCGEN
#define _UBER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define Vehiculos 8

struct Posicion {
	int x;
	int y;
};
typedef struct Posicion Posicion;

struct Uber {
	char placas[10];
	bool_t disponible;
	Posicion posicion;
	int tarifa;
	char tipo[15];
};
typedef struct Uber Uber;

struct Servicio {
	int viajesRealizados;
	int numAutos;
	int ganancia;
};
typedef struct Servicio Servicio;

struct TerminarViajeArgs {
	Posicion final;
	int costoViaje;
	char placas[10];
};
typedef struct TerminarViajeArgs TerminarViajeArgs;

#define uber_prog 0x20000003
#define uber_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define solicitarViaje 1
extern  Uber * solicitarviaje_1(Posicion , CLIENT *);
extern  Uber * solicitarviaje_1_svc(Posicion , struct svc_req *);
#define TerminarViaje 2
extern  void * terminarviaje_1(TerminarViajeArgs , CLIENT *);
extern  void * terminarviaje_1_svc(TerminarViajeArgs , struct svc_req *);
#define estadoServicio 3
extern  Servicio * estadoservicio_1(CLIENT *);
extern  Servicio * estadoservicio_1_svc(struct svc_req *);
extern int uber_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicitarViaje 1
extern  Uber * solicitarviaje_1();
extern  Uber * solicitarviaje_1_svc();
#define TerminarViaje 2
extern  void * terminarviaje_1();
extern  void * terminarviaje_1_svc();
#define estadoServicio 3
extern  Servicio * estadoservicio_1();
extern  Servicio * estadoservicio_1_svc();
extern int uber_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Posicion (XDR *, Posicion*);
extern  bool_t xdr_Uber (XDR *, Uber*);
extern  bool_t xdr_Servicio (XDR *, Servicio*);
extern  bool_t xdr_TerminarViajeArgs (XDR *, TerminarViajeArgs*);

#else /* K&R C */
extern bool_t xdr_Posicion ();
extern bool_t xdr_Uber ();
extern bool_t xdr_Servicio ();
extern bool_t xdr_TerminarViajeArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UBER_H_RPCGEN */
