/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "uber.h"
#include <time.h>



Uber listaUbers[Vehiculos];

Servicio servicio = {0, 0, 0};

void inicializarUbers() {
    for (int i = 0; i < Vehiculos; i++) {
        sprintf(listaUbers[i].placas, "UBER%03d", i);
        listaUbers[i].disponible = true;
        listaUbers[i].posicion.x = rand() % 50;
        listaUbers[i].posicion.y = rand() % 50;
        if (i % 3 == 0){	
			strcpy(listaUbers[i].tipo, "UberPlanet");
        	listaUbers[i].tarifa = 10;
		}
        else if (i % 3 == 1){
            strcpy(listaUbers[i].tipo, "UberXL");
			listaUbers[i].tarifa = 15;
		}
		else{
            strcpy(listaUbers[i].tipo, "UberBlack");
			listaUbers[i].tarifa = 25;
		}
		}
}



Uber *
solicitarviaje_1_svc(Posicion pasajero,  struct svc_req *rqstp)
{
	static Uber  result;
    float minDist = 10000.0;
    bool viajeEncontrado = false;
    int i = 0;
    while (!viajeEncontrado && i<Vehiculos) {
        if (listaUbers[i].disponible) {
            float dist = sqrt(pow(listaUbers[i].posicion.x - pasajero.x, 2) + pow(listaUbers[i].posicion.y - pasajero.y, 2));
            if (dist < minDist) {
                minDist = dist;
                result = listaUbers[i];
                viajeEncontrado = true;
            }
        }
        i++;
    }
    if (viajeEncontrado)
    {
        return &result;
    }
    else
    {
        return NULL;
    }
     
}

void *
terminarviaje_1_svc(TerminarViajeArgs args,  struct svc_req *rqstp)
{
	static char * result;
    //Actualizar la información del Uber
    for (int i = 0; i < Vehiculos; i++) {
        if (strcmp(listaUbers[i].placas, args.placas) == 0) {
            listaUbers[i].posicion = args.final;
            listaUbers[i].disponible = true;
            break;
        }
    }
    
    servicio.viajesRealizados += 1;
    servicio.ganancia += args.costoViaje;
    args.pos.x = rand() % 50;
    args.pos.y = rand() % 50;

	return (void *) &result;

}

Servicio *
estadoservicio_1_svc(struct svc_req *rqstp)
{
	static Servicio  result;

    pruintf("Viajes realizados: %d\n", servicio.viajesRealizados);

    printf("Ganancia total: %.2f\n", servicio.ganancia);

    for (int i = 0; i < Vehiculos; i++)
    {
        if (listaUbers[i].disponible) {
            servicio.numAutos += 1;
        }
    }
    
    printf("Numero de autos: %d\n", servicio.numAutos);

	return &result;
}
