/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "uber.h"
#include <time.h>



Uber listaUbers[Vehiculos];


void inicializarUbers() {
    for (int i = 0; i < Vehiculos; i++) {
        sprintf(listaUbers[i].placas, "UBER%03d", i);
        listaUbers[i].disponible = true;
        listaUbers[i].posicion.x = rand() % 50;
        listaUbers[i].posicion.y = rand() % 50;
        if (i % 3 == 0){	
			strcpy(listaUbers[i].tipo, "UberPlanet");
        	listaUbers[i].tarifa = 10;
		}
        else if (i % 3 == 1){
            strcpy(listaUbers[i].tipo, "UberXL");
			listaUbers[i].tarifa = 15;
		}
		else{
            strcpy(listaUbers[i].tipo, "UberBlack");
			listaUbers[i].tarifa = 25;
		}
		}
}



Uber *
solicitarviaje_1_svc(Posicion pasajero,  struct svc_req *rqstp)
{
	static Uber  result;

	for (int i = 0; i < 8; i++) {
		     printf("\nSolicitud de viaje recibida.\n");
                bool viaje_encontrado = false;

                while (!viaje_encontrado && i<Vehiculos)
                {
                    int i = 0;
                    if (Uber[i].disponible)
                    {
                        int costo = rand() % 100 + 50;
                        sprintf(viaje, "%s %d %d", Uber[i].placas, costo, i);
                        Uber[i].disponible=false;
                        send(socket_nuevo_fd, viaje, strlen(viaje)+1, 0);
                        viaje_encontrado = true;
                        ganancia += costo;
                        totalViajes++; 	
                    }
                    i++;
                }
                if (!viaje_encontrado){
                    strcpy(viaje, "No hay conductores");
                    send(socket_nuevo_fd, viaje, strlen(viaje)+1, 0);
                }
	}
	return &result;
}

void *
terminarviaje_1_svc(TerminarViajeArgs args,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	for (int i = 0; i < 10; i++) {
		result[i] = args.placas[i];
	}


	return (void *) &result;
}

Servicio *
estadoservicio_1_svc(struct svc_req *rqstp)
{
	static Servicio  result;

	/*
	 * insert server code here
	 */

	return &result;
}
